# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('champion', models.CharField(max_length=20)),
                ('lane', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('winner', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('wards_placed', models.IntegerField()),
                ('wards_killed', models.IntegerField()),
            ],
            options={
                'db_table': 'Junction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=20)),
                ('time_stamp', models.FloatField()),
                ('match_duration', models.FloatField()),
            ],
            options={
                'db_table': 'Matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('summoner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('summoner_name', models.CharField(max_length=20)),
                ('winrate', models.FloatField()),
                ('cs', models.FloatField()),
                ('kills', models.FloatField()),
                ('deaths', models.FloatField()),
                ('assists', models.FloatField()),
                ('kda', models.FloatField()),
                ('gold', models.FloatField()),
                ('cs_per_min', models.FloatField()),
                ('gold_per_min', models.FloatField()),
                ('wards_placed', models.FloatField()),
                ('wards_killed', models.FloatField()),
                ('matches_played', models.FloatField()),
            ],
            options={
                'db_table': 'Summoners',
                'managed': False,
            },
        ),
    ]
